package edu.model;

/**
 * 课程参数模型
 * 
 * @author wgt
 * @date 17-12-14
 */
public class CourseModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.id
     *
     * @mbggenerated
     */
    private int id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.c_no
     *
     * @mbggenerated
     */
    private String cNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.c_name
     *
     * @mbggenerated
     */
    private String cName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.c_credit
     *
     * @mbggenerated
     */
    private int cCredit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.c_perid
     *
     * @mbggenerated
     */
    private int cPerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.t_no
     *
     * @mbggenerated
     */
    private int tNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.c_grade
     *
     * @mbggenerated
     */
    private int cGrade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.c_address
     *
     * @mbggenerated
     */
    private String cAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.c_week_time
     *
     * @mbggenerated
     */
    private String cWeekTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.c_number
     *
     * @mbggenerated
     */
    private int cNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.c_desc
     *
     * @mbggenerated
     */
    private String cDesc;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getcNo() {
        return cNo;
    }

    public void setcNo(String cNo) {
        this.cNo = cNo;
    }

    public String getcName() {
        return cName;
    }

    public void setcName(String cName) {
        this.cName = cName;
    }

    public int getcCredit() {
        return cCredit;
    }

    public void setcCredit(int cCredit) {
        this.cCredit = cCredit;
    }

    public int getcPerid() {
        return cPerid;
    }

    public void setcPerid(int cPerid) {
        this.cPerid = cPerid;
    }

    public int gettNo() {
        return tNo;
    }

    public void settNo(int tNo) {
        this.tNo = tNo;
    }

    public int getcGrade() {
        return cGrade;
    }

    public void setcGrade(int cGrade) {
        this.cGrade = cGrade;
    }

    public String getcAddress() {
        return cAddress;
    }

    public void setcAddress(String cAddress) {
        this.cAddress = cAddress;
    }

    public String getcWeekTime() {
        return cWeekTime;
    }

    public void setcWeekTime(String cWeekTime) {
        this.cWeekTime = cWeekTime;
    }

    public int getcNumber() {
        return cNumber;
    }

    public void setcNumber(int cNumber) {
        this.cNumber = cNumber;
    }

    public String getcDesc() {
        return cDesc;
    }

    public void setcDesc(String cDesc) {
        this.cDesc = cDesc;
    }
}
