package edu.model;

import java.io.Serializable;

public class Course implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.c_no
     *
     * @mbggenerated
     */
    private String cNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.c_name
     *
     * @mbggenerated
     */
    private String cName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.c_credit
     *
     * @mbggenerated
     */
    private Integer cCredit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.c_perid
     *
     * @mbggenerated
     */
    private Integer cPerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.t_no
     *
     * @mbggenerated
     */
    private Integer tNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.c_grade
     *
     * @mbggenerated
     */
    private String cGrade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.c_address
     *
     * @mbggenerated
     */
    private String cAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.c_week_time
     *
     * @mbggenerated
     */
    private String cWeekTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.c_number
     *
     * @mbggenerated
     */
    private Integer cNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.c_desc
     *
     * @mbggenerated
     */
    private String cDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table course
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.id
     *
     * @return the value of course.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.id
     *
     * @param id the value for course.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.c_no
     *
     * @return the value of course.c_no
     *
     * @mbggenerated
     */
    public String getcNo() {
        return cNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.c_no
     *
     * @param cNo the value for course.c_no
     *
     * @mbggenerated
     */
    public void setcNo(String cNo) {
        this.cNo = cNo == null ? null : cNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.c_name
     *
     * @return the value of course.c_name
     *
     * @mbggenerated
     */
    public String getcName() {
        return cName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.c_name
     *
     * @param cName the value for course.c_name
     *
     * @mbggenerated
     */
    public void setcName(String cName) {
        this.cName = cName == null ? null : cName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.c_credit
     *
     * @return the value of course.c_credit
     *
     * @mbggenerated
     */
    public Integer getcCredit() {
        return cCredit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.c_credit
     *
     * @param cCredit the value for course.c_credit
     *
     * @mbggenerated
     */
    public void setcCredit(Integer cCredit) {
        this.cCredit = cCredit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.c_perid
     *
     * @return the value of course.c_perid
     *
     * @mbggenerated
     */
    public Integer getcPerid() {
        return cPerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.c_perid
     *
     * @param cPerid the value for course.c_perid
     *
     * @mbggenerated
     */
    public void setcPerid(Integer cPerid) {
        this.cPerid = cPerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.t_no
     *
     * @return the value of course.t_no
     *
     * @mbggenerated
     */
    public Integer gettNo() {
        return tNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.t_no
     *
     * @param tNo the value for course.t_no
     *
     * @mbggenerated
     */
    public void settNo(Integer tNo) {
        this.tNo = tNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.c_grade
     *
     * @return the value of course.c_grade
     *
     * @mbggenerated
     */
    public String getcGrade() {
        return cGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.c_grade
     *
     * @param cGrade the value for course.c_grade
     *
     * @mbggenerated
     */
    public void setcGrade(String cGrade) {
        this.cGrade = cGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.c_address
     *
     * @return the value of course.c_address
     *
     * @mbggenerated
     */
    public String getcAddress() {
        return cAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.c_address
     *
     * @param cAddress the value for course.c_address
     *
     * @mbggenerated
     */
    public void setcAddress(String cAddress) {
        this.cAddress = cAddress == null ? null : cAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.c_week_time
     *
     * @return the value of course.c_week_time
     *
     * @mbggenerated
     */
    public String getcWeekTime() {
        return cWeekTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.c_week_time
     *
     * @param cWeekTime the value for course.c_week_time
     *
     * @mbggenerated
     */
    public void setcWeekTime(String cWeekTime) {
        this.cWeekTime = cWeekTime == null ? null : cWeekTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.c_number
     *
     * @return the value of course.c_number
     *
     * @mbggenerated
     */
    public Integer getcNumber() {
        return cNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.c_number
     *
     * @param cNumber the value for course.c_number
     *
     * @mbggenerated
     */
    public void setcNumber(Integer cNumber) {
        this.cNumber = cNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.c_desc
     *
     * @return the value of course.c_desc
     *
     * @mbggenerated
     */
    public String getcDesc() {
        return cDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.c_desc
     *
     * @param cDesc the value for course.c_desc
     *
     * @mbggenerated
     */
    public void setcDesc(String cDesc) {
        this.cDesc = cDesc == null ? null : cDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Course other = (Course) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getcNo() == null ? other.getcNo() == null : this.getcNo().equals(other.getcNo()))
            && (this.getcName() == null ? other.getcName() == null : this.getcName().equals(other.getcName()))
            && (this.getcCredit() == null ? other.getcCredit() == null : this.getcCredit().equals(other.getcCredit()))
            && (this.getcPerid() == null ? other.getcPerid() == null : this.getcPerid().equals(other.getcPerid()))
            && (this.gettNo() == null ? other.gettNo() == null : this.gettNo().equals(other.gettNo()))
            && (this.getcGrade() == null ? other.getcGrade() == null : this.getcGrade().equals(other.getcGrade()))
            && (this.getcAddress() == null ? other.getcAddress() == null : this.getcAddress().equals(other.getcAddress()))
            && (this.getcWeekTime() == null ? other.getcWeekTime() == null : this.getcWeekTime().equals(other.getcWeekTime()))
            && (this.getcNumber() == null ? other.getcNumber() == null : this.getcNumber().equals(other.getcNumber()))
            && (this.getcDesc() == null ? other.getcDesc() == null : this.getcDesc().equals(other.getcDesc()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getcNo() == null) ? 0 : getcNo().hashCode());
        result = prime * result + ((getcName() == null) ? 0 : getcName().hashCode());
        result = prime * result + ((getcCredit() == null) ? 0 : getcCredit().hashCode());
        result = prime * result + ((getcPerid() == null) ? 0 : getcPerid().hashCode());
        result = prime * result + ((gettNo() == null) ? 0 : gettNo().hashCode());
        result = prime * result + ((getcGrade() == null) ? 0 : getcGrade().hashCode());
        result = prime * result + ((getcAddress() == null) ? 0 : getcAddress().hashCode());
        result = prime * result + ((getcWeekTime() == null) ? 0 : getcWeekTime().hashCode());
        result = prime * result + ((getcNumber() == null) ? 0 : getcNumber().hashCode());
        result = prime * result + ((getcDesc() == null) ? 0 : getcDesc().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", cNo=").append(cNo);
        sb.append(", cName=").append(cName);
        sb.append(", cCredit=").append(cCredit);
        sb.append(", cPerid=").append(cPerid);
        sb.append(", tNo=").append(tNo);
        sb.append(", cGrade=").append(cGrade);
        sb.append(", cAddress=").append(cAddress);
        sb.append(", cWeekTime=").append(cWeekTime);
        sb.append(", cNumber=").append(cNumber);
        sb.append(", cDesc=").append(cDesc);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}