package edu.model;

/**
 * 课程参数模型
 * 
 * @author wgt
 * @date 17-12-14
 */
public class CourseParam {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.c_no
     *
     * @mbggenerated
     */
    private String cNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.c_name
     *
     * @mbggenerated
     */
    private String cName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.c_credit
     *
     * @mbggenerated
     */
    private String cCredit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.c_perid
     *
     * @mbggenerated
     */
    private String cPerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.t_no
     *
     * @mbggenerated
     */
    private String tNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.c_grade
     *
     * @mbggenerated
     */
    private String cGrade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.c_address
     *
     * @mbggenerated
     */
    private String cAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.c_week_time
     *
     * @mbggenerated
     */
    private String cWeekTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.c_number
     *
     * @mbggenerated
     */
    private String cNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.c_desc
     *
     * @mbggenerated
     */
    private String cDesc;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getcNo() {
        return cNo;
    }

    public void setcNo(String cNo) {
        this.cNo = cNo;
    }

    public String getcName() {
        return cName;
    }

    public void setcName(String cName) {
        this.cName = cName;
    }

    public String getcCredit() {
        return cCredit;
    }

    public void setcCredit(String cCredit) {
        this.cCredit = cCredit;
    }

    public String getcPerid() {
        return cPerid;
    }

    public void setcPerid(String cPerid) {
        this.cPerid = cPerid;
    }

    public String gettNo() {
        return tNo;
    }

    public void settNo(String tNo) {
        this.tNo = tNo;
    }

    public String getcGrade() {
        return cGrade;
    }

    public void setcGrade(String cGrade) {
        this.cGrade = cGrade;
    }

    public String getcAddress() {
        return cAddress;
    }

    public void setcAddress(String cAddress) {
        this.cAddress = cAddress;
    }

    public String getcWeekTime() {
        return cWeekTime;
    }

    public void setcWeekTime(String cWeekTime) {
        this.cWeekTime = cWeekTime;
    }

    public String getcNumber() {
        return cNumber;
    }

    public void setcNumber(String cNumber) {
        this.cNumber = cNumber;
    }

    public String getcDesc() {
        return cDesc;
    }

    public void setcDesc(String cDesc) {
        this.cDesc = cDesc;
    }
}
