package edu.model;

import java.io.Serializable;

public class CurriculaVariableInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column curricula_variable_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column curricula_variable_info.c_c_no
     *
     * @mbggenerated
     */
    private Integer cCNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column curricula_variable_info.c_s_no
     *
     * @mbggenerated
     */
    private Integer cSNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column curricula_variable_info.c_t_no
     *
     * @mbggenerated
     */
    private Integer cTNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column curricula_variable_info.c_mark
     *
     * @mbggenerated
     */
    private Integer cMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column curricula_variable_info.c_status
     *
     * @mbggenerated
     */
    private Integer cStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table curricula_variable_info
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column curricula_variable_info.id
     *
     * @return the value of curricula_variable_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column curricula_variable_info.id
     *
     * @param id the value for curricula_variable_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column curricula_variable_info.c_c_no
     *
     * @return the value of curricula_variable_info.c_c_no
     *
     * @mbggenerated
     */
    public Integer getcCNo() {
        return cCNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column curricula_variable_info.c_c_no
     *
     * @param cCNo the value for curricula_variable_info.c_c_no
     *
     * @mbggenerated
     */
    public void setcCNo(Integer cCNo) {
        this.cCNo = cCNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column curricula_variable_info.c_s_no
     *
     * @return the value of curricula_variable_info.c_s_no
     *
     * @mbggenerated
     */
    public Integer getcSNo() {
        return cSNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column curricula_variable_info.c_s_no
     *
     * @param cSNo the value for curricula_variable_info.c_s_no
     *
     * @mbggenerated
     */
    public void setcSNo(Integer cSNo) {
        this.cSNo = cSNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column curricula_variable_info.c_t_no
     *
     * @return the value of curricula_variable_info.c_t_no
     *
     * @mbggenerated
     */
    public Integer getcTNo() {
        return cTNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column curricula_variable_info.c_t_no
     *
     * @param cTNo the value for curricula_variable_info.c_t_no
     *
     * @mbggenerated
     */
    public void setcTNo(Integer cTNo) {
        this.cTNo = cTNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column curricula_variable_info.c_mark
     *
     * @return the value of curricula_variable_info.c_mark
     *
     * @mbggenerated
     */
    public Integer getcMark() {
        return cMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column curricula_variable_info.c_mark
     *
     * @param cMark the value for curricula_variable_info.c_mark
     *
     * @mbggenerated
     */
    public void setcMark(Integer cMark) {
        this.cMark = cMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column curricula_variable_info.c_status
     *
     * @return the value of curricula_variable_info.c_status
     *
     * @mbggenerated
     */
    public Integer getcStatus() {
        return cStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column curricula_variable_info.c_status
     *
     * @param cStatus the value for curricula_variable_info.c_status
     *
     * @mbggenerated
     */
    public void setcStatus(Integer cStatus) {
        this.cStatus = cStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curricula_variable_info
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CurriculaVariableInfo other = (CurriculaVariableInfo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getcCNo() == null ? other.getcCNo() == null : this.getcCNo().equals(other.getcCNo()))
            && (this.getcSNo() == null ? other.getcSNo() == null : this.getcSNo().equals(other.getcSNo()))
            && (this.getcTNo() == null ? other.getcTNo() == null : this.getcTNo().equals(other.getcTNo()))
            && (this.getcMark() == null ? other.getcMark() == null : this.getcMark().equals(other.getcMark()))
            && (this.getcStatus() == null ? other.getcStatus() == null : this.getcStatus().equals(other.getcStatus()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curricula_variable_info
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getcCNo() == null) ? 0 : getcCNo().hashCode());
        result = prime * result + ((getcSNo() == null) ? 0 : getcSNo().hashCode());
        result = prime * result + ((getcTNo() == null) ? 0 : getcTNo().hashCode());
        result = prime * result + ((getcMark() == null) ? 0 : getcMark().hashCode());
        result = prime * result + ((getcStatus() == null) ? 0 : getcStatus().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curricula_variable_info
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", cCNo=").append(cCNo);
        sb.append(", cSNo=").append(cSNo);
        sb.append(", cTNo=").append(cTNo);
        sb.append(", cMark=").append(cMark);
        sb.append(", cStatus=").append(cStatus);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}