package edu.model;

/**
 * 用户参数模型
 * 
 * @author wgt
 * @date 17-12-13
 */
public class UserParam {

    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_num
     *
     * @mbggenerated
     */
    private String uNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_passwd
     *
     * @mbggenerated
     */
    private String uPasswd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_type
     *
     * @mbggenerated
     */
    private String uType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_name
     *
     * @mbggenerated
     */
    private String uName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_gender
     *
     * @mbggenerated
     */
    private String uGender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_grade
     *
     * @mbggenerated
     */
    private String uGrade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_major
     *
     * @mbggenerated
     */
    private String uMajor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_key
     *
     * @mbggenerated
     */
    private String uKey;


    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getuNum() {
        return uNum;
    }

    public void setuNum(String uNum) {
        this.uNum = uNum;
    }

    public String getuPasswd() {
        return uPasswd;
    }

    public void setuPasswd(String uPasswd) {
        this.uPasswd = uPasswd;
    }

    public String getuType() {
        return uType;
    }

    public void setuType(String uType) {
        this.uType = uType;
    }

    public String getuName() {
        return uName;
    }

    public void setuName(String uName) {
        this.uName = uName;
    }

    public String getuGender() {
        return uGender;
    }

    public void setuGender(String uGender) {
        this.uGender = uGender;
    }

    public String getuGrade() {
        return uGrade;
    }

    public void setuGrade(String uGrade) {
        this.uGrade = uGrade;
    }

    public String getuMajor() {
        return uMajor;
    }

    public void setuMajor(String uMajor) {
        this.uMajor = uMajor;
    }

    public String getuKey() {
        return uKey;
    }

    public void setuKey(String uKey) {
        this.uKey = uKey;
    }
}
