package edu.dao;

import edu.model.CurriculaVariableInfo;

import java.util.List;

public interface CurriculaVariableInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curricula_variable_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curricula_variable_info
     *
     * @mbggenerated
     */
    int insert(CurriculaVariableInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curricula_variable_info
     *
     * @mbggenerated
     */
    int insertSelective(CurriculaVariableInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curricula_variable_info
     *
     * @mbggenerated
     */
    CurriculaVariableInfo selectByPrimaryKey(Integer id);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curricula_variable_info
     *
     * @mbggenerated
     */
    List<CurriculaVariableInfo> selectCurriculaVariableInfosByCno(Integer cNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curricula_variable_info
     *
     * @mbggenerated
     */
    List<CurriculaVariableInfo> selectCurriculaVariableInfosBySno(Integer sNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curricula_variable_info
     *
     * @mbggenerated
     */
    List<CurriculaVariableInfo> selectSuccessCurriculaVariableInfosBySno(Integer sNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curricula_variable_info
     *
     * @mbggenerated
     */
    List<CurriculaVariableInfo> selectCurriculaVariableInfosByTno(Integer tNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curricula_variable_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CurriculaVariableInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curricula_variable_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CurriculaVariableInfo record);
}